### PR TITLE
Dungeon Random rooms and corridors between them Generation

### LINKED ISSUE #1: Dungeon Random rooms and corridors between them Generation

### LINKED ISSUE #2: split large rooms into two smaller one's
Без разделения на меньшие комнаты игрок будет сталкиваться со слишком большими комнатами, имеющими слишком мало выходов. А учитывая особенности перемещения игрока (кулдаун), это явно создаст трудности. К тому же, имея некое разделение на большие и небольшие комнаты, можно будет серьезно упростить генерацию локаций, сделав её намного более универсальной. Хоть она мне и сейчас нравится.

Image

### PR DESCRIPTION
**Pull request by the-asind**
Closed #1 issue
Resolved #2 issue
image
image
image

### CODE REVIEW

**Comment by the-asind** [comment]
image
image
image
Three different types of generation

**Review by Alexey-Sagaydak — COMMENTED** [review]
Ok

**Review by TheNorth322 — COMMENTED** [review]
pull confirmed

**Review by TheNorth322 — APPROVED** [review]
pull confirmed

**Pull request merged**
